services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - AWS_REGION=${AWS_REGION}
      - MONGODB_SECRET_NAME=${MONGODB_SECRET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped