name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build and push backend image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/login-backend:latest ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/login-backend:latest

    - name: Build and push frontend image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/login-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/login-frontend:latest
    - name: Upload files to EC2
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./"
        target: "/home/${{ secrets.EC2_USER }}/project"
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          mkdir -p /home/${{ secrets.EC2_USER }}/project
          rsync -avz --exclude '.git' ./ /home/${{ secrets.EC2_USER }}/project/
          cd /home/${{ secrets.EC2_USER }}/project
          export VITE_API_URL=http://${{ secrets.EC2_PUBLIC_IP }}
          docker-compose pull
          docker-compose up -d --force-recreate